// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using portfolio_backend.Contexts;

#nullable disable

namespace portfoliobackend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("portfolio_backend.Models.Project", b =>
                {
                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.HasKey("Link");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
